stages:
  - Frontend Static Analysis
  - Frontend Test
  - Python Static Analysis
  - Python Test

variables:
  IN_CI: "true"

black:
  image: "python:3.9"
  stage: Python Static Analysis
  script:
    - cd server
    - pip install poetry
    - poetry install --no-root
    - poetry run black --check .

pytest:
  image: "python:3.9"
  stage: Python Test
  script:
    - cd server
    - pip install poetry
    - poetry install --no-root
    - poetry run pytest --cov=src .

prettier:
  image: "node:alpine"
  stage: Frontend Static Analysis
  script:
    - cd roomee-fe
    - yarn install
    - yarn prettier --check .

jest:
  image: "node:alpine"
  stage: Fronted Test
  script:
    - cd roomee-fe
    - yarn install
    - yarn test
